# Given a dictionary of inventory, stock and price & funds amount, add a feature
# to provide a discount to shoppers that give a discount code.

import math

# Store information
store_account = 100
# Generated by ChatGPT, a very useful way to use the application
store_inventory = {
    1: {"name": "Apple", "price": 1, "stock": 150, "category": "Fruits"},
    2: {"name": "Banana", "price": 1, "stock": 120, "category": "Fruits"},
    3: {"name": "Chicken Breast", "price": 5, "stock": 60, "category": "Meat"},
    4: {"name": "Broccoli", "price": 2, "stock": 90, "category": "Vegetables"},
    5: {"name": "Almonds", "price": 10, "stock": 30, "category": "Nuts"},
    6: {"name": "Milk", "price": 3, "stock": 100, "category": "Dairy"},
    7: {"name": "Bread", "price": 2, "stock": 80, "category": "Bakery"},
    8: {"name": "Eggs", "price": 4, "stock": 200, "category": "Dairy"},
    9: {"name": "Salmon", "price": 15, "stock": 40, "category": "Seafood"},
    10: {"name": "Lettuce", "price": 2, "stock": 70, "category": "Vegetables"},
    11: {"name": "Orange", "price": 1, "stock": 110, "category": "Fruits"},
    12: {"name": "Beef Steak", "price": 12, "stock": 50, "category": "Meat"},
    13: {"name": "Carrots", "price": 1, "stock": 95, "category": "Vegetables"},
    14: {"name": "Walnuts", "price": 8, "stock": 40, "category": "Nuts"},
    15: {"name": "Cheese", "price": 6, "stock": 70, "category": "Dairy"},
    16: {"name": "Bagel", "price": 3, "stock": 60, "category": "Bakery"},
    17: {"name": "Yogurt", "price": 2, "stock": 130, "category": "Dairy"},
    18: {"name": "Shrimp", "price": 13, "stock": 35, "category": "Seafood"},
    19: {"name": "Tomato", "price": 1, "stock": 85, "category": "Vegetables"},
    20: {"name": "Grapes", "price": 2, "stock": 140, "category": "Fruits"},
    21: {"name": "Pork Chops", "price": 7, "stock": 45, "category": "Meat"},
    22: {"name": "Spinach", "price": 2, "stock": 80, "category": "Vegetables"},
    23: {"name": "Cashews", "price": 9, "stock": 25, "category": "Nuts"},
    24: {"name": "Butter", "price": 4, "stock": 75, "category": "Dairy"},
    25: {"name": "Croissant", "price": 3, "stock": 55, "category": "Bakery"},
    26: {"name": "Cream Cheese", "price": 3, "stock": 90, "category": "Dairy"},
    27: {"name": "Crab", "price": 18, "stock": 20, "category": "Seafood"},
    28: {"name": "Cucumber", "price": 1, "stock": 100, "category": "Vegetables"},
    29: {"name": "Strawberries", "price": 3, "stock": 110, "category": "Fruits"},
    30: {"name": "Turkey Breast", "price": 8, "stock": 55, "category": "Meat"},
    31: {"name": "Kale", "price": 2, "stock": 65, "category": "Vegetables"},
    32: {"name": "Pistachios", "price": 11, "stock": 35, "category": "Nuts"},
    33: {"name": "Sour Cream", "price": 2, "stock": 80, "category": "Dairy"},
    34: {"name": "Muffin", "price": 2, "stock": 75, "category": "Bakery"},
    35: {"name": "Ricotta", "price": 4, "stock": 60, "category": "Dairy"},
    36: {"name": "Lobster", "price": 20, "stock": 15, "category": "Seafood"},
    37: {"name": "Bell Pepper", "price": 2, "stock": 85, "category": "Vegetables"},
    38: {"name": "Blueberries", "price": 4, "stock": 120, "category": "Fruits"},
    39: {"name": "Lamb Chops", "price": 14, "stock": 30, "category": "Meat"},
    40: {"name": "Zucchini", "price": 1, "stock": 95, "category": "Vegetables"},
    41: {"name": "Hazelnuts", "price": 10, "stock": 20, "category": "Nuts"},
    42: {"name": "Whipped Cream", "price": 3, "stock": 70, "category": "Dairy"},
    43: {"name": "Donut", "price": 2, "stock": 65, "category": "Bakery"},
    44: {"name": "Mozzarella", "price": 5, "stock": 80, "category": "Dairy"},
    45: {"name": "Clams", "price": 12, "stock": 25, "category": "Seafood"},
    46: {"name": "Eggplant", "price": 2, "stock": 75, "category": "Vegetables"},
    47: {"name": "Raspberries", "price": 4, "stock": 100, "category": "Fruits"},
    48: {"name": "Sausage", "price": 7, "stock": 50, "category": "Meat"},
    49: {"name": "Celery", "price": 1, "stock": 90, "category": "Vegetables"},
    50: {"name": "Peanuts", "price": 5, "stock": 60, "category": "Nuts"},
    51: {"name": "Ghee", "price": 8, "stock": 40, "category": "Dairy"},
    52: {"name": "Pancake", "price": 3, "stock": 50, "category": "Bakery"},
    53: {"name": "Parmesan", "price": 6, "stock": 70, "category": "Dairy"},
    54: {"name": "Oysters", "price": 15, "stock": 20, "category": "Seafood"},
    55: {"name": "Mushroom", "price": 2, "stock": 80, "category": "Vegetables"},
    56: {"name": "Blackberries", "price": 4, "stock": 110, "category": "Fruits"},
    57: {"name": "Bacon", "price": 6, "stock": 65, "category": "Meat"},
    58: {"name": "Asparagus", "price": 3, "stock": 60, "category": "Vegetables"},
    59: {"name": "Macadamia Nuts", "price": 12, "stock": 15, "category": "Nuts"},
    60: {"name": "Greek Yogurt", "price": 4, "stock": 75, "category": "Dairy"},
    61: {"name": "Bagel", "price": 3, "stock": 60, "category": "Bakery"},
    62: {"name": "Feta", "price": 5, "stock": 55, "category": "Dairy"},
    63: {"name": "Scallops", "price": 16, "stock": 18, "category": "Seafood"},
    64: {"name": "Radish", "price": 1, "stock": 70, "category": "Vegetables"},
    65: {"name": "Peaches", "price": 3, "stock": 95, "category": "Fruits"},
    66: {"name": "Duck Breast", "price": 13, "stock": 35, "category": "Meat"},
    67: {"name": "Brussels Sprouts", "price": 2, "stock": 65, "category": "Vegetables"},
    68: {"name": "Pecans", "price": 9, "stock": 25, "category": "Nuts"},
    69: {"name": "Cottage Cheese", "price": 3, "stock": 70, "category": "Dairy"},
    70: {"name": "Brownie", "price": 3, "stock": 40, "category": "Bakery"},
    71: {"name": "Gouda", "price": 6, "stock": 50, "category": "Dairy"},
    72: {"name": "Mussels", "price": 11, "stock": 30, "category": "Seafood"},
    73: {"name": "Cauliflower", "price": 2, "stock": 85, "category": "Vegetables"},
    74: {"name": "Apricots", "price": 3, "stock": 90, "category": "Fruits"},
    75: {"name": "Veal Cutlet", "price": 15, "stock": 25, "category": "Meat"},
    76: {"name": "Turnip", "price": 1, "stock": 50, "category": "Vegetables"},
    77: {"name": "Chestnuts", "price": 8, "stock": 20, "category": "Nuts"},
    78: {"name": "Heavy Cream", "price": 3, "stock": 80, "category": "Dairy"},
    79: {"name": "Eclair", "price": 3, "stock": 50, "category": "Bakery"},
    80: {"name": "Provolone", "price": 5, "stock": 60, "category": "Dairy"},
    81: {"name": "Squid", "price": 14, "stock": 20, "category": "Seafood"},
    82: {"name": "Leek", "price": 2, "stock": 70, "category": "Vegetables"},
    83: {"name": "Pineapple", "price": 3, "stock": 85, "category": "Fruits"},
    84: {"name": "Rabbit", "price": 12, "stock": 30, "category": "Meat"},
    85: {"name": "Collard Greens", "price": 2, "stock": 55, "category": "Vegetables"},
    86: {"name": "Walnuts", "price": 8, "stock": 40, "category": "Nuts"},
    87: {"name": "Mascarpone", "price": 5, "stock": 50, "category": "Dairy"},
    88: {"name": "Tiramisu", "price": 4, "stock": 45, "category": "Bakery"},
    89: {"name": "Swiss Cheese", "price": 6, "stock": 55, "category": "Dairy"},
    90: {"name": "Tilapia", "price": 10, "stock": 35, "category": "Seafood"},
    91: {"name": "Pumpkin", "price": 3, "stock": 65, "category": "Vegetables"},
    92: {"name": "Plums", "price": 3, "stock": 75, "category": "Fruits"}
}

discounts = {
    "Fruits": 0.8,
    "Vegetables": 0.9
}


def sell_item(item_id: int, discount_code: str = None):
    '''Given an item id, remove the item from inventory and add funds to the store account'''
    global store_account, store_inventory
    discount = 1
    if discount_code != None and store_inventory[item_id]["category"] == discount_code:
        discount = discounts[discount_code]
    store_account += math.floor(store_inventory[item_id]["price"] * discount)
    store_inventory[item_id]["stock"] -= 1
    return True

def buy_item(item_id: int, amount: int, total_cost: int):
    '''Given an item id, the number of items, and the cost of the order, add the items into inventory and subtract funds'''
    global store_account, store_inventory
    store_account -= total_cost
    store_inventory[item_id]["stock"] += amount
    return True

def update_item_price(item_id: int, new_price: int):
    '''Given an item id and new price, change the price of an item'''
    global store_inventory
    store_inventory[item_id]["price"] = new_price
    return True

print("Start of Day $", store_account)
sell_item(1, "Fruits")
sell_item(2, "Fruits")
sell_item(11, "Fruits")
sell_item(13, "Vegetables")
sell_item(40, "Vegetables")
sell_item(49, "Vegetables")
sell_item(19, "Vegetables")
sell_item(64, "Vegetables")
sell_item(76, "Vegetables")
print("End of Day $", store_account)

def csv_to_dict(text):
    lines = [line for line in text.split("\n") if line.strip()]
    

    if not lines:
        return []
    
    dkeys = lines[0].split(",")

    output = []
    for line in lines[1:]:
        values = line.split(",")
        sample = {dkeys[i]: values[i] for i in range(len(dkeys))}
        output.append(sample)
    
    return output
